relativeURLs = true
title = "Ajit Sharma"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Professor of Technology, Innovation and Entrepreneurship, Wayne State University"
    logo = "gr.jpg" 
    
